### ISSUE TITLE
Class 'Yansongda\\LaravelNotificationWechat\\DefaultCredential' not found at vendor/yansongda/laravel-notification-wechat/src/WechatChannel.php:52

### ISSUE THREAD

**Issue by zhengwhizz** [yansongda/laravel-notification-wechat#5]
Class 'Yansongda\\LaravelNotificationWechat\\DefaultCredential' not found at vendor/yansongda/laravel-notification-wechat/src/WechatChannel.php:52

**Comment by yansongda** [comment]
composer update 

感谢您的支持
